/**
 * This package contains:
 * <ol>
 * <li> The classes generated by Antlr4
 * <li> The classes MiniZinc2* used to obtain the Java model
 * </ol>
 */
/**
 * @author rafa
 *
 */
package minizinc.antlr4;